### ISSUE TITLE
Question: Dockerfile for primekey/ejbca-ce:latest

### ISSUE THREAD

**Issue by jisnardo** [primekeydevs/ejbca-ce#1]
Hi,

could you share the Dockerfile for primekey/ejbca-ce:latest?

https://hub.docker.com/layers/primekey/ejbca-ce/latest/images/sha256-7398f097e9af53e569b158155f4c7dc13c4f462bf9111df43f6854e59aeab6c6?context=explore

Maybe upload it to https://github.com/primekeydevs/containers?

Thanks.

**Comment by pkjohan** [comment]
Hi Jorge,

There is unfortunately no simple `Containerfile`. The `primekey/ejbca-ce:latest` images are created by a larger build system that can also build `primekey/signserver-ce` and other versions of these apps and more.

Are there any particular tweaks or customization options you miss?

/J

**Comment by jisnardo** [comment]
Hi @pkjohan only curiosity. Thanks!

**Comment by ralienpp** [comment]
@pkjohan, I was looking for the same thing, to find out what features I can tweak by manipulating environment variables. Specifically, I'd like EJBCA to start with CMP over TCP enabled.

I'm considering creating a tutorial about CMP, and EJBCA comes in handy, because it is an effortless way of creating a CA that speaks CMP. All one has to do is run `docker run -it --rm -p 80:8080 -p 443:8443 -h mycahostname -e TLS_SETUP_ENABLED="simple" keyfactor/ejbca-ce`.

However, I'd like the configuration to be as automated as possible, such that a newbie can be certain the server is in the right state, so there's nothing else they have to tinker with. Is there documentation about these environment variables?
